## ATENCAO PRO AMBIENTE HOMOLOG: PORTA BANCO 3307 E PORTA WEB 9090!
server:
  error:
    include-stacktrace: on_param
#  port: 9090
spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/vip
    username: jefao
    password: jefao



logging:
  level:
    org:
      springframework:
          r2dbc: DEBUG