server:
  error:
    include-stacktrace: on_param # ?trace=true
    include-message: always

spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/vip
    username: ${DB_USER:jefao}
    password: ${DB_PASS:jefao}

## ATENCAO DESATIVA LOG DE SQL
logging:
  level:
    org:
      springframework:
          r2dbc: ${DATABASE_LOG_LEVEL:DEBUG}