version: "3"
services:
#  api:
#    build: .
#    ports:
#      - 8080:8080
#    networks:
#      - whats-network
  db-vip-whats:
    image: mariadb:10.9.2
    environment:
      - MYSQL_ROOT_PASSWORD=jefao123
      - MYSQL_DATABASE=vip
      - MYSQL_USER=jefao
      - MYSQL_PASSWORD=jefao
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
#    networks:
#      - whats-network

#networks:
#  whats-network: